# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66476535ae4d6f274dc81711f2d06bee82f2361705ece4b90e8e6cac5d56ffc1a1931ec1e7caedf38e96d02ce44398680e9b4bf2327632a6a20874ae2080f7a5

test:
  secret_key_base: c5922841c7f98bac2b6f71b556cf02ba20666e5b75a5cbe69445f12bc38b102d36d4697fe8ba9f8e055dcc8280c0acddf1135a17047958a5d1fcd5779ae4b68d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
